name: Publish on releases

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build and publish to Space Packages
        uses: burrunan/gradle-cache-action@v1
        env:
          # GPG keys for signing plugin (sign maven artifacts)
          # see https://docs.gradle.org/current/userguide/signing_plugin.html#sec:in-memory-keys
          # ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SECRET_ASCII_ARMORED }}
          # ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSWORD }}

          ORG_GRADLE_PROJECT_spaceUsername: ${{ secrets.JB_SPACE_CLIENT_ID }}
          ORG_GRADLE_PROJECT_spacePassword: ${{ secrets.JB_SPACE_CLIENT_SECRET }}
        with:
          # jobs with different JDK versions can't share caches
          job-id: jdk17
          arguments: publish
          properties: version=${{ github.event.release.tag_name }}
