name: Manual release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "New semver version without Notary API version suffix"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Test build before release
        uses: burrunan/gradle-cache-action@v1
        with:
          # jobs with different JDK versions can't share caches
          job-id: jdk17
          arguments: build

      - name: Read Notary API version
        uses: pCYSl5EDgo/cat@master
        id: notary-api-version
        with:
          path: notary-api-version.txt
          trim: true

      - name: Compute release tag (with protocol version)
        run: echo "::set-output name=tag::${{ github.event.inputs.version }}-${{ steps.notary-api-version.outputs.text }}"
        id: compute-tag

      - name: Generate Change Log
        uses: burrunan/gradle-cache-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # jobs with different JDK versions can't share caches
          job-id: jdk17
          # We already deal with caches in a previous gradle-cache-action
          execution-only-caches: true
          arguments: generateChangelog
          properties: version=${{ steps.compute-tag.outputs.tag }}

      - name: Commit and Push Change Log
        id: changelog-commit
        run: |
          git config user.name '${{ github.actor }}'
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          git add CHANGELOG.md
          git commit -m "Version ${{ steps.compute-tag.outputs.tag }}"
          git push
          echo "::set-output name=sha::$(git rev-parse HEAD)"
      - name: Create Release and Tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }} # using personal token to trigger publish workflow
        with:
          tag_name: ${{ steps.compute-tag.outputs.tag }}
          release_name: ${{ steps.compute-tag.outputs.tag }}
          commitish: ${{ steps.changelog-commit.outputs.sha }}